export const STOCKS_DATA = [
    // Low Volatility / Conservative
    { id: 1, ticker: 'JNJ', name: '존슨앤드존슨', volatility: 'Low', expectedReturn3M: 1.5 },
    { id: 2, ticker: 'PG', name: '프로스터 앤 갬블', volatility: 'Low', expectedReturn3M: 1.8 },
    { id: 3, ticker: 'KO', name: '코카콜라', volatility: 'Low', expectedReturn3M: 1.2 },
    { id: 4, ticker: 'PEP', name: '펩시코', volatility: 'Low', expectedReturn3M: 1.4 },
    { id: 5, ticker: 'WM', name: '웨이스트 매니지먼트', volatility: 'Low', expectedReturn3M: 2.1 },
    { id: 6, ticker: 'COST', name: '코스트코', volatility: 'Low', expectedReturn3M: 3.0 },
    { id: 7, ticker: 'V', name: '비자', volatility: 'Low', expectedReturn3M: 2.8 },
    { id: 8, ticker: 'MRK', name: '머크', volatility: 'Low', expectedReturn3M: 2.5 },
    { id: 9, ticker: 'UNH', name: '유나이티드헬스', volatility: 'Low', expectedReturn3M: 2.9 },
    { id: 10, ticker: 'BRK.B', name: '버크셔 해서웨이', volatility: 'Low', expectedReturn3M: 3.2 },
    { id: 11, ticker: 'MCD', name: '맥도날드', volatility: 'Low', expectedReturn3M: 1.7 },
    { id: 12, ticker: 'WMT', name: '월마트', volatility: 'Low', expectedReturn3M: 2.3 },
    { id: 13, ticker: 'HD', name: '홈디포', volatility: 'Low', expectedReturn3M: 2.6 },
    { id: 14, ticker: 'CVX', name: '쉐브론', volatility: 'Low', expectedReturn3M: 1.9 },
    { id: 15, ticker: 'XOM', name: '엑슨모빌', volatility: 'Low', expectedReturn3M: 2.0 },
    { id: 16, ticker: 'PFE', name: '화이자', volatility: 'Low', expectedReturn3M: 0.8 },
    { id: 17, ticker: 'VZ', name: '버라이즌', volatility: 'Low', expectedReturn3M: 1.0 },
    { id: 18, ticker: 'T', name: 'AT&T', volatility: 'Low', expectedReturn3M: 0.9 },
    { id: 19, ticker: 'NEE', name: '넥스테라 에너지', volatility: 'Low', expectedReturn3M: 2.4 },
    { id: 20, ticker: 'DUK', name: '듀크 에너지', volatility: 'Low', expectedReturn3M: 1.5 },

    // Medium Volatility / Balanced
    { id: 21, ticker: 'AAPL', name: '애플', volatility: 'Medium', expectedReturn3M: 4.5 },
    { id: 22, ticker: 'MSFT', name: '마이크로소프트', volatility: 'Medium', expectedReturn3M: 5.0 },
    { id: 23, ticker: 'GOOGL', name: '알파벳', volatility: 'Medium', expectedReturn3M: 4.8 },
    { id: 24, ticker: 'AMZN', name: '아마존', volatility: 'Medium', expectedReturn3M: 5.5 },
    { id: 25, ticker: 'META', name: '메타', volatility: 'Medium', expectedReturn3M: 6.0 },
    { id: 26, ticker: 'JPM', name: 'JPMorgan', volatility: 'Medium', expectedReturn3M: 3.5 },
    { id: 27, ticker: 'BAC', name: '뱅크오브아메리카', volatility: 'Medium', expectedReturn3M: 3.2 },
    { id: 28, ticker: 'DIS', name: '디즈니', volatility: 'Medium', expectedReturn3M: 2.8 },
    { id: 29, ticker: 'NFLX', name: '넷플릭스', volatility: 'Medium', expectedReturn3M: 5.8 },
    { id: 30, ticker: 'ADBE', name: '어도비', volatility: 'Medium', expectedReturn3M: 4.0 },
    { id: 31, ticker: 'CRM', name: '세일즈포스', volatility: 'Medium', expectedReturn3M: 4.2 },
    { id: 32, ticker: 'INTC', name: '인텔', volatility: 'Medium', expectedReturn3M: 2.0 },
    { id: 33, ticker: 'CSCO', name: '시스코', volatility: 'Medium', expectedReturn3M: 2.5 },
    { id: 34, ticker: 'QCOM', name: '퀄컴', volatility: 'Medium', expectedReturn3M: 4.6 },
    { id: 35, ticker: 'TXN', name: '텍사스 인스트루먼트', volatility: 'Medium', expectedReturn3M: 3.8 },

    // High Volatility / Aggressive
    { id: 36, ticker: 'MSTR', name: '마이크로스트레티지', volatility: 'High', expectedReturn3M: 18.5 },
    { id: 37, ticker: 'COIN', name: '코인베이스', volatility: 'High', expectedReturn3M: 15.0 },
    { id: 38, ticker: 'SMCI', name: '슈퍼마이크로', volatility: 'High', expectedReturn3M: 22.0 },
    { id: 39, ticker: 'TSLA', name: '테슬라', volatility: 'High', expectedReturn3M: 12.5 },
    { id: 40, ticker: 'PLTR', name: '팔란티어', volatility: 'High', expectedReturn3M: 14.0 },
    { id: 41, ticker: 'NVDA', name: '엔비디아', volatility: 'High', expectedReturn3M: 11.5 },
    { id: 42, ticker: 'ARM', name: 'ARM 홀딩스', volatility: 'High', expectedReturn3M: 13.0 },
    { id: 43, ticker: 'HOOD', name: '로빈후드', volatility: 'High', expectedReturn3M: 16.5 },
    { id: 44, ticker: 'ROKU', name: '로쿠', volatility: 'High', expectedReturn3M: 9.5 },
    { id: 45, ticker: 'AMD', name: 'AMD', volatility: 'High', expectedReturn3M: 10.0 },
    { id: 46, ticker: 'CVNA', name: '카바나', volatility: 'High', expectedReturn3M: 25.0 },
    { id: 47, ticker: 'SOFI', name: '소파이', volatility: 'High', expectedReturn3M: 11.0 },
    { id: 48, ticker: 'U', name: '유니티 소프트웨어', volatility: 'High', expectedReturn3M: 8.5 },
    { id: 49, ticker: 'SNOW', name: '스노우플레이크', volatility: 'High', expectedReturn3M: 10.5 },
    { id: 50, ticker: 'SHOP', name: '쇼피파이', volatility: 'High', expectedReturn3M: 11.8 }
];
